<a href="https://colab.research.google.com/github/sandeep92134/The-Data-Science-Workshop-By-Packt/blob/master/module%2014/Activity14.01%3A%20Fitting%20a%20Logistic%20Regression%20Model%20on%20a%20High-Dimensional%20Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [3]:
# Defining the file name from github
filename = 'https://raw.githubusercontent.com/sandeep92134/The-Data-Science-Workshop-By-Packt/master/module%2014/datasets/ad.data'

In [4]:
# Loading the data using pandas
adData = pd.read_csv(filename,sep=",",header = None,error_bad_lines=False)
adData.head()

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (3) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

   0     1       2    3     4     5     ...  1553  1554  1555  1556  1557  1558
0   125   125     1.0    1     0     0  ...     0     0     0     0     0   ad.
1    57   468  8.2105    1     0     0  ...     0     0     0     0     0   ad.
2    33   230  6.9696    1     0     0  ...     0     0     0     0     0   ad.
3    60   468     7.8    1     0     0  ...     0     0     0     0     0   ad.
4    60   468     7.8    1     0     0  ...     0     0     0     0     0   ad.

[5 rows x 1559 columns]

In [5]:
# Seperating the dependent and independent variables
# Preparing the X variables
X = adData.loc[:,0:1557]
print(X.shape)
# Preparing the Y variable
Y = adData[1558]
print(Y.shape)

(3279, 1558)
(3279,)

In [6]:
# Replacing special characters in first 3 columns which are of type object
for i in range(0,3):
  X[i] = X[i].str.replace("?", 'NaN').values.astype(float)
print(X.head(15))

     0      1       2    3     4     5     ...  1552  1553  1554  1555  1556  1557
0   125.0  125.0  1.0000    1     0     0  ...     0     0     0     0     0     0
1    57.0  468.0  8.2105    1     0     0  ...     0     0     0     0     0     0
2    33.0  230.0  6.9696    1     0     0  ...     0     0     0     0     0     0
3    60.0  468.0  7.8000    1     0     0  ...     0     0     0     0     0     0
4    60.0  468.0  7.8000    1     0     0  ...     0     0     0     0     0     0
5    60.0  468.0  7.8000    1     0     0  ...     0     0     0     0     0     0
6    59.0  460.0  7.7966    1     0     0  ...     0     0     0     0     0     0
7    60.0  234.0  3.9000    1     0     0  ...     0     0     0     0     0     0
8    60.0  468.0  7.8000    1     0     0  ...     0     0     0     0     0     0
9    60.0  468.0  7.8000    1     0     0  ...     0     0     0     0     0     0
10    NaN    NaN     NaN    1     0     0  ...     0     0     0     0     0     0
11   90.0   52.0  0.5777    1     0     0  ...     0     0     0     0     0     0
12   90.0   60.0  0.6666    1     0     0  ...     0     0     0     0     0     0
13   90.0   60.0  0.6666    1     0     0  ...     0     0     0     0     0     0
14   33.0  230.0  6.9696    1     0     0  ...     0     0     0     0     0     0

[15 rows x 1558 columns]

In [7]:
# Replacing special characters in the remaining columns which are of type integer
for i in range(3,1557):
  X[i] = X[i].replace("?", 'NaN').values.astype(float)

In [8]:
import numpy as np
# Imputing the NaN'  with mean of the values
for i in range(0,1557):
  X[i] = X[i].fillna(X[i].mean())
  
print(X.head(15))

          0           1         2     3     4     ...  1553  1554  1555  1556  1557
0   125.000000  125.000000  1.000000   1.0   0.0  ...   0.0   0.0   0.0   0.0     0
1    57.000000  468.000000  8.210500   1.0   0.0  ...   0.0   0.0   0.0   0.0     0
2    33.000000  230.000000  6.969600   1.0   0.0  ...   0.0   0.0   0.0   0.0     0
3    60.000000  468.000000  7.800000   1.0   0.0  ...   0.0   0.0   0.0   0.0     0
4    60.000000  468.000000  7.800000   1.0   0.0  ...   0.0   0.0   0.0   0.0     0
5    60.000000  468.000000  7.800000   1.0   0.0  ...   0.0   0.0   0.0   0.0     0
6    59.000000  460.000000  7.796600   1.0   0.0  ...   0.0   0.0   0.0   0.0     0
7    60.000000  234.000000  3.900000   1.0   0.0  ...   0.0   0.0   0.0   0.0     0
8    60.000000  468.000000  7.800000   1.0   0.0  ...   0.0   0.0   0.0   0.0     0
9    60.000000  468.000000  7.800000   1.0   0.0  ...   0.0   0.0   0.0   0.0     0
10   64.021886  155.344828  3.911953   1.0   0.0  ...   0.0   0.0   0.0   0.0     0
11   90.000000   52.000000  0.577700   1.0   0.0  ...   0.0   0.0   0.0   0.0     0
12   90.000000   60.000000  0.666600   1.0   0.0  ...   0.0   0.0   0.0   0.0     0
13   90.000000   60.000000  0.666600   1.0   0.0  ...   0.0   0.0   0.0   0.0     0
14   33.000000  230.000000  6.969600   1.0   0.0  ...   0.0   0.0   0.0   0.0     0

[15 rows x 1558 columns]

In [9]:
# Normalising the data sets
# Import library function
from sklearn import preprocessing
# Creating the scaling function
minmaxScaler = preprocessing.MinMaxScaler()
# Transforming with the scaler function
X_tran = pd.DataFrame(minmaxScaler.fit_transform(X))
# Printing the output
X_tran.head()

       0         1         2     3     4     ...  1553  1554  1555  1556  1557
0  0.194053  0.194053  0.016642   1.0   0.0  ...   0.0   0.0   0.0   0.0   0.0
1  0.087637  0.730829  0.136820   1.0   0.0  ...   0.0   0.0   0.0   0.0   0.0
2  0.050078  0.358372  0.116138   1.0   0.0  ...   0.0   0.0   0.0   0.0   0.0
3  0.092332  0.730829  0.129978   1.0   0.0  ...   0.0   0.0   0.0   0.0   0.0
4  0.092332  0.730829  0.129978   1.0   0.0  ...   0.0   0.0   0.0   0.0   0.0

[5 rows x 1558 columns]

In [10]:
# Creating a high dimension data set
X_hd = pd.DataFrame(pd.np.tile(X_tran, (1, 300)))

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead

In [11]:
# Printing the dimension of the data set
X_hd.shape

(3279, 467400)

In [12]:
from sklearn.model_selection import train_test_split
# Splitting the data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X_hd, Y, test_size=0.3, random_state=123)

In [13]:
from sklearn.linear_model import LogisticRegression
import time
# Defining the LogisticRegression function
benchmarkModel = LogisticRegression()
# Starting a timing function
t0=time.time()
# Fitting the model
benchmarkModel.fit(X_train, y_train)
# Finding the end time 

print("Total training time:", round(time.time()-t0, 3), "s")

Total training time: 112.317 s

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)

In [14]:
# Predicting using the model
pred = benchmarkModel.predict(X_test)
print('Accuracy of Logistic regression model prediction on test set: {:.2f}'.format(benchmarkModel.score(X_test, y_test)))

Accuracy of Logistic regression model prediction on test set: 0.97

In [15]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
# Confusion Matrix for the model
print(confusion_matrix(y_test, pred))
# Classification report for the model
print(classification_report(y_test, pred))

[[112  14]
 [ 14 844]]
              precision    recall  f1-score   support

         ad.       0.89      0.89      0.89       126
      nonad.       0.98      0.98      0.98       858

    accuracy                           0.97       984
   macro avg       0.94      0.94      0.94       984
weighted avg       0.97      0.97      0.97       984